#! /bin/bash
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/docker/compose/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
COMPOSE_URL="https://github.com/docker/compose/releases/download/$LATEST_VERSION/docker-compose-Linux-x86_64"
COMPOSE_BASH_COMP_URL="https://raw.githubusercontent.com/docker/compose/$LATEST_VERSION/contrib/completion/bash/docker-compose"
COMPOSE_ZSH_COMP_URL="https://raw.githubusercontent.com/docker/compose/$LATEST_VERSION/contrib/completion/zsh/_docker-compose"

rm -f -- /usr/local/bin/docker-compose
sudo curl -L COMPOSE_URL -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

sudo curl -L $COMPOSE_BASH_COMP_URL -o /etc/bash_completion.d/docker-compose
mkdir -p ~/.zsh/completion
rm -f -- ~/.zsh/completion/_docker-compose
curl -L $COMPOSE_ZSH_COMP_URL > ~/.zsh/completion/_docker-compose
